=== wongkunheng/chapter4B/xsddemo/menu.xsd
<?xml version="1.0"?>
<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">
  <xs:element name="menu">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="item" type="itemType" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  <xs:complexType name="itemType">
    <xs:sequence>
      <xs:element name="code" type="xs:integer"/>
      <xs:element name="name" type="xs:string"/>
      <xs:element name="price" type="xs:float"/>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== wongkunheng/chapter4B/xsddemo/menuH.xml
<?xml version="1.0" encoding="UTF-8"?>
<menu
  xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
  xsi:noNamespaceSchemaLocation='menu.xsd'>
  <item>
    <code>1001</code>
    <name>Nasi Lemak Ayam</name>
    <price>10.90</price>
  </item>
  <item>
    <code>1002</code>
    <name>Pineapple Fried Rice</name>
    <price>20.00</price>
  </item>
  <item>
    <code>1003</code>
    <name>Ice Lemon Tea</name>
    <price>5.00</price>
  </item>
</menu>
