=== wongkunheng/chapter4B/xsddemo/orderVB.xsd
<?xml version="1.0"?>
<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">
  
  <xs:complexType name="deliverToType">
    <xs:sequence>
      <xs:element name="officeNo" type="xs:string"/>
      <xs:element name="building" type="xs:string"/>
      <xs:element name="phone" type="xs:string" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="itemType">
    <xs:sequence>
      <xs:element name="name" type="xs:string"/>
      <xs:element name="quantity" type="xs:positiveInteger"/>
      <xs:element name="price" type="xs:decimal"/>
    </xs:sequence>
  </xs:complexType>
  
  <xs:complexType name="orderType">
    <xs:sequence>
      <xs:element name="customer" type="xs:string"/>
      <xs:element name="deliverTo" type="deliverToType"/>
      <xs:element name="item" type="itemType" maxOccurs="unbounded"/>
    </xs:sequence> 
    <xs:attribute name="orderID" type="xs:string" use="required"/>
  </xs:complexType>
  
  <xs:element name="order" type="orderType" />


</xs:schema>

=== wongkunheng/chapter4B/xsddemo/order.xml
<?xml version="1.0" encoding="UTF-8"?>

<order orderID="12"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="orderVB.xsd">
  <customer>Jane Doe</customer>
  <deliverTo>
    <officeNo>A102</officeNo>
    <building>Bangunan TSKKB</building>
    <phone>010-12345678</phone>
  </deliverTo>
  <item>
    <name>Nasi Lemak Biasa</name>
    <quantity>2</quantity>
    <price>1.50</price>
  </item>
  <item>
    <name>Macaroni and Cheese</name>
    <quantity>3</quantity>
    <price>4.50</price>
  </item>
</order>
