=== wongkunheng/chapter4B/xsddemo/participants.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT participants (student*)>
<!ELEMENT student (name, regNo)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT regNo (#PCDATA)>

=== wongkunheng/chapter4B/xsddemo/participants.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE participants SYSTEM 'participants.dtd'>

<participants>
  <student>
    <name>Jane Doe</name>
    <regNo>16WMR12345</regNo>
  </student>
   <student>
    <name>Don Juan</name>
    <regNo>16WMR88888</regNo>
  </student> 
  <student>
    <name>Mary Brown</name>
    <regNo>16WMR78910</regNo>
  </student>
  
</participants>
