=== wongkunheng/chapter4B/dtddemo/members.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT members (member*)>
<!ELEMENT member (name, age)>
<!ATTLIST member  id ID #REQUIRED
                  spouse_id IDREF #IMPLIED
                  parent_id IDREFS #IMPLIED>
<!ELEMENT name (#PCDATA)>
<!ELEMENT age (#PCDATA)>

=== wongkunheng/chapter4B/dtddemo/members.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE members SYSTEM 'members.dtd'>
<members>
  <member id="F1234">
    <name>Fred Flinstone</name>
    <age>45</age>
  </member>
  <member id="A5678" spouse_id="F1234">
    <name>Wilma Amber</name>
    <age>38</age>
  </member>
  <member id="F8888" parent_id="F1234 A5678">
    <name>Pebbles Flinstone</name>
    <age>5</age>
  </member>
</members>
